apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.appName }}-ingress"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    kubernetes.io/ingress.class: "traefik"
spec:
  tls:
  - hosts:
    - exdatic.com
    secretName: "{{ .Values.appName }}-staging-tls"
  rules:
  - host: exdatic.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.appName }}
            port:
              number: 3000
